#ANSA_GENERAL_COMMENT;~
#$ Project:     SK3165EUB~
#$ Description: Common crash car assembly~
#$ Responsible: Jan Blaha, jan.blaha@skoda-auto.cz, EKF~
#$~
#$ Modification history:~
#$~
#n SK3165EUB_BIQ_car_001_2015~
#i   Simplified CAR according to CAD from 04.12.2018~
#d   11.12.2018~
#a   Martin Jodas, IDIADA~
#c     - Halter STF were modified to avoid intersection with Spoiler~
#c     - renumbered in range~
#c     - Headlamps taken from P-release~
#c     - Unpenetrated with respect to RBU~
#c     - Sets for Pendulum defined~
#r     - car for Pendulum~
###############################################################################~
#;
#ANSA_USER_ATTRIBUTES;SK3165EUB_BIQ_car_001_2015.inc;INCLUDE;DM/IO Index;TEXT;14
#;
#
#
#
#---5---10----5---20----5---30----5---40----5---50----5---60----5---70----5---80
NODE  /   2500013314.55135441445-742.13255526472 448.40919600193

