#ANSA_GENERAL_COMMENT;~
#$ Project:     SK316_5CS~
#$ Description: Rear bumper~
#$ Responsible: Jan Stekly, jan.stekly@idiada.com, Applus IDIADA Group~
#$~
#$ Modification history:~
#$~
#n SK3165EUB_AIQ_rear_bumper_003_2015~
#i   rear bumper model for pendel test +23C~
#d   6.12.2018~
#a   Lukas Kadlec, IDIADA CZ~
#c     - source:~
#c       5LG_807_000____GEO_TM__001_____ZIERLEISTE_________B-FREI____2018_11_22~
#c       5LG_807_000____GEO_TMG_000_____AHK_VERSTAERKERUNG_B-FREI____2018_11_26~
#c       5LG_807_393____GEO_TM__003_____FUEHRUNGSPROFIL_LI_PS-24622______181122~
#c       5LG_807_393_A__GEO_TM__003_____FUEHRUNGSP_SBBR_LI_PS-24623______181121~
#c       5LG_807_421____GEO_TM__001_____ABDECKUNG_HINTEN_________________181122~
#c       5LG_807_441____GEO_TM__003_____ABDECKUNG_ABSCHLEP_______________181126~
#c       5LG_807_521_H__GEO_TM__002_000_SPOILER________________________181126__~
#c       5LG_807_568____GEO_TM__001_____DIFUZOR____________B-FREI____2018_11_26~
#c       5LG_807_863____GEO_TM__003_____BEFESTIGUNGSLEISTE_______A_______181126~
#c      - Abdeckung and Befestigunsleiste were updated according to 2018_12_3~
#c      - MID defined according to SKODA AUTO definition for temperature +23C~
#r      - model for pendel test~
#n SK3165EUB_BIQ_rear_bumper_003_2015~
#i   rear bumper model for pendel test +23C~
#d   11.12.2018~
#a   Lukas Kadlec, IDIADA CZ~
#c      - Include was renamed~
#r      - model for pendel test~
###############################################################################~
#;
#---5---10----5---20----5---30----5---40----5---50----5---60----5---70----5---80
NODE  / 195000003616.18206795061450.957902735401104.655581251674
