#ANSA_GENERAL_COMMENT;~
#$ Project:     SK3165EUB~
#$ Description: Insurance reinforcement assembly~
#$ Responsible: J. Jirkovsky, ext.jaroslav.jirkovsky2@skoda-auto.cz, TK/42~
#$~
#$ Modification history:~
#$~
#n SK3165EUB_AIB_rear_defo_012_2015~
#i   CMS VW - 11.10.2018~
#d   15.10.2018~
#a   Martin Vybostok, Evektor~
#c     - source CAD:~
#c     11A_807_305_DMU_EN__001_TRAEGER_STOSSF_HI__RICHTUNG_B-FR_181011.CATPart~
#c     - CMS based on CAD data~
#c     - Depenetrated with car~
#r     - New development state~
#n SK3165EUB_AIB_rear_defo_018_2015~
#i   SQTR+Schliessplatte CAD 24.10.2018~
#d   06.11.2018~
#a   Jan Prajza, Evektor~
#c     - source CAD:~
#c     ZWA_SK316_-_ZADNI_VYZTUHA-1.CATPart~
#c     - Upgrade SQTR+Schottplatte according CAD 24.10.2018~
#c     - Depenetrated with car~
#r     - New development state~
#n SK3165EUB_AIB_rear_defo_022_2015~
#i   Changed mater of defo from HX420LAD to DP780~
#d   21.11.2018~
#a   Jan Prajza, Evektor~
#c     - Changed mater of defo from HX420LAD to DP780~
#r     - New development state~
#n SK3165EUB_AIB_rear_defo_024_2015~
#i   Changed thickness of defo from 1,7/2,2mm->1,7/1,7mm~
#d   23.11.2018~
#a   Jan Prajza, Evektor~
#c     - Changed thickness of defo from 1,7/2,2mm->1,7/1,7mm~
#r     - New development state~
#n SK3165EUB_AIB_rear_defo_025_2015~
#i   Changed thickness of defo 1,9/1,9mm~
#d   23.11.2018~
#a   Jan Prajza, Evektor~
#c     - Changed thickness of defo 1,9/1,9mm~
#r     - New development state~
#n SK3165EUB_AIB_rear_defo_026_2015~
#i   Changed thickness of defo 1,8/1,8mm~
#d   28.11.2018~
#a   Jan Prajza, Evektor~
#c     - Changed thickness of defo 1,8/1,8mm~
#r     - New development state~
#n SK3165EUB_AIB_rear_defo_029_2015~
#i   Added welds to Inner and Outer side of defo~
#d   30.11.2018~
#a   Martin Vybostok, Evektor~
#c     - Added welds to Inner and Outer side of defo~
#r     - New development state~
#n SK3165EUB_AIB_rear_defo_031_2015~
#i   Modified welds~
#d   03.12.2018~
#a   Jan Prajza, Evektor~
#c     - Modified welds~
#r     - New development state~
#n SK3165EUB_AIB_rear_defo_032_2015~
#i   Modified welds II.~
#d   03.12.2018~
#a   Jan Prajza, Evektor~
#c     - Modified welds II.~
#r     - New development state~
#n SK3165EUB_BIB_rear_defo_033_2015~
#i   Depenetrated, add groups~
#d   14.12.2018~
#a   Martin Jodas, IDIADA CZ~
#c     - Depenetrated foam~
#c     - Add group: RDE_CNTAC_10_FGS_foam~
#c     - Add group: RDE_TIED_S_FGS_foam_connection~
#c     - Add group: RDE_TIED_M_FGS_foam_connection~
#c     - Add group: tied_abschleppoese_master~
#c     - Add group: RDE_RBODY_mounting_global~
#c     - Add CNTACs: RDE_FGS_foam,  RDE_FGS_foam_connection~
#r     - Renamed include by pendulum convetion~
###############################################################################~
#;
#---5---10----5---20----5---30----5---40----5---50----5---60----5---70----5---80
#ANSA_FROZEN_ID;50180;NODE;YES;
#ANSA_NAME;50180;NODE;~
#RDE_FIXNO_50180
NODE  /    50180          3359.2-511.60838776202158.209918556951
#ANSA_FROZEN_ID;50181;NODE;YES;
#ANSA_NAME;50181;NODE;~
#RDE_FIXNO_50181
NODE  /    50181          3359.2-401.38954152008158.207021245482
#ANSA_FROZEN_ID;50182;NODE;YES;
#ANSA_NAME;50182;NODE;~
#RDE_FIXNO_50182
NODE  /    50182          3359.2-511.4973107577712.9238416940063
#ANSA_FROZEN_ID;50183;NODE;YES;
#ANSA_NAME;50183;NODE;~
#RDE_FIXNO_50183
NODE  /    50183          3359.2401.389541520079158.207021245482
#ANSA_FROZEN_ID;50184;NODE;YES;
#ANSA_NAME;50184;NODE;~
#RDE_FIXNO_50184
NODE  /    50184          3359.2 511.60838776202158.209918556951
#ANSA_FROZEN_ID;50185;NODE;YES;
#ANSA_NAME;50185;NODE;~
#RDE_FIXNO_50185
NODE  /    50185          3359.2 401.4666318148612.9957787882261
#ANSA_FROZEN_ID;50186;NODE;YES;
#ANSA_NAME;50186;NODE;~
#RDE_FIXNO_50186
NODE  /    50186          3359.2511.49731075776812.9238416940063
#ANSA_FROZEN_ID;50187;NODE;YES;
#ANSA_NAME;50187;NODE;~
#RDE_FIXNO_50187
NODE  /    50187          3359.2-410.56384807899 15.285284157348
#ANSA_FROZEN_ID;50357;NODE;YES;
#ANSA_NAME;50357;NODE;~
#RDE_FIXNO_50357
NODE  /    503573558.18285387841-458.1802862374579.3138787086597
#ANSA_FROZEN_ID;50358;NODE;YES;
#ANSA_NAME;50358;NODE;~
#RDE_FIXNO_50358
NODE  /    503583624.99999441843-.00120351804216116.783310641558
#ANSA_FROZEN_ID;50359;NODE;YES;
#ANSA_NAME;50359;NODE;~
#RDE_FIXNO_50359
NODE  /    503593563.28016213522438.27339354685786.2024815189528
